// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    connectId: '606535B47BCB68B9286E',
    secretKey: 'c061512a567b49+3a1b3d80EDb4a79/012Ace042',
    adspace: '1615657'
  };

}).call(this);
