// Generated by CoffeeScript 1.3.3
(function() {
  var Zanox, adspace, config, connectId, id, secretKey, zanox, _ref;

  Zanox = require('../lib/Zanox');

  _ref = config = require('./config'), connectId = _ref.connectId, secretKey = _ref.secretKey, adspace = _ref.adspace;

  zanox = Zanox(connectId, secretKey);
  
  id = 'e4a2aae8f0883c5ddbbeac8b8806b0e2';

  zanox.getProduct(id, function(err, data) {
    if (err != null) {
      return console.log('error', err);
    }
    return console.log('%j', data);
  });

}).call(this);
