// Generated by CoffeeScript 1.3.3
(function() {
  var Zanox, admediaParams, adspace, config, connectId, params, secretKey, zanox, _ref;

  Zanox = require('../lib/Zanox');

  _ref = config = require('./config'), connectId = _ref.connectId, secretKey = _ref.secretKey, adspace = _ref.adspace;

  zanox = Zanox(connectId, secretKey);

  params = {
    adspace: adspace,
    status: 'confirmed'
  };

  admediaParams = {};

  zanox.getAdmedia({}, console.log);

}).call(this);
